// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var $dateranger, $end_date, $selectable_options, $start_date, applyDateRange, placeholder;
    $dateranger = $('#dateranger');
    $selectable_options = $('#dateranger-selectable_options');
    $start_date = $('#dateranger-start_date');
    $end_date = $('#dateranger-end_date');
    placeholder = function() {
      return $('#dateranger-date_range_placeholder').html("" + ($start_date.val()) + " - " + ($end_date.val()));
    };
    applyDateRange = function(start_date, end_date) {
      $dateranger.dateranger('setStartDate', start_date);
      return $dateranger.dateranger('setEndDate', end_date);
    };
    placeholder();
    $('#dateranger-apply').click(function() {
      return placeholder();
    });
    $dateranger.dateranger({
      onSelectStartDate: function(date) {
        $end_date.addClass('selected');
        return $start_date.removeClass('selected').val($.datepicker.formatDate('mm/dd/yy', date));
      },
      onSelectEndDate: function(date) {
        $start_date.addClass('selected');
        $end_date.removeClass('selected').val($.datepicker.formatDate('mm/dd/yy', date));
        return $selectable_options.val("" + ($start_date.val()) + "-" + ($end_date.val()));
      }
    });
    $start_date.change(function() {
      return applyDateRange($start_date.val(), $end_date.val());
    });
    $end_date.change(function() {
      return applyDateRange($start_date.val(), $end_date.val());
    });
    return $selectable_options.change(function() {
      return applyDateRange.apply(null, $(this).val().split('-'));
    });
  });

}).call(this);
